application: live-fm
version: 1
runtime: python
api_version: 1

handlers:
- url: /scripts
  static_dir: scripts
  
- url: /images
  static_dir: images

- url: /updateCache
  script: Server.py
  login: admin
  
- url: /.*
  script: Server.py